#!/bin/bash
aws configure set default.region us-east-1
aws ec2 authorize-security-group-ingress --group-name default --protocol tcp --port 22 --cidr 0.0.0.0/0 --query 'ok' --output text
aws ec2 create-key-pair --key-name ss --query 'KeyMaterial' --output text > ss.pem

aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
clear
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
clear
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --query 'sieusao'  --output text
clear
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://C:\bash.txt --query 'sieusao'  --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 95 --image-id ami-083654bd07b5da81d --instance-type c5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
clear
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type c6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
clear
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r6i.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type r5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 47 --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 47 --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 47 --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 47 --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 47 --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 47 --image-id ami-083654bd07b5da81d --instance-type r5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 63 --image-id ami-083654bd07b5da81d --instance-type m5a.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 31 --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1a --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 31 --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1b --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 31 --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1c --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 31 --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1d --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 31 --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1e --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
aws ec2 run-instances --count 31 --image-id ami-083654bd07b5da81d --instance-type m5ad.large --key-name ss --placement Tenancy=dedicated,AvailabilityZone=us-east-1f --user-data file://~/bash.txt --instance-initiated-shutdown-behavior terminate --query 'sieusao' --output text
clear
